import logging
from collections.abc import Sequence
from pathlib import Path

from rag_etl.resources import BaseResource
from rag_etl.transformers.base_transformer import BaseTransformer
from rag_etl.transformers.merge_slide_transcript.utils import parse_srt, text_between
import rag_etl.utils.mime_types as mt

logger = logging.getLogger(__name__)

# The transcript is quoted rather than put under a heading
TRANSCRIPT_PREFIX = "> "


def slide_start_seconds(resource: BaseResource) -> int:
    """
    Return the second the slide's interval starts at.

    VideoToFramesTransformer names each frame after that moment, and the name
    survives the conversion to Markdown, so the file name carries it.
    """

    return int(Path(resource.path).stem)


class MergeSlideTranscriptTransformer(BaseTransformer):
    """
    Transformer that appends to each slide the words spoken over it.

    Slides come out of the vision model carrying only what is written on
    them, which is the scaffold of the lecture rather than its substance.
    Appending the matching stretch of transcript puts both in the same chunk,
    so a question answered out loud retrieves the slide it was answered on.

    Resources without a transcript, or that are not Markdown slides, are left
    unchanged.
    """

    def __init__(self, type_subtypes=None, **kwargs) -> None:
        super().__init__(**kwargs)

        self.type_subtypes = type_subtypes

    def group_by_video(self, resources: Sequence[BaseResource]) -> dict[str, list[BaseResource]]:
        """
        Group slide resources by the transcript they share.

        Slides of every video arrive interleaved in one flat list. Bucketing
        them by their transcript puts each video's slides together, so the SRT
        is parsed once and every slide can be bounded by the next one.

        Args:
            resources (Sequence[BaseResource]): Slides, in any order.

        Returns:
            dict[str, list[BaseResource]]: Slides by transcript path, each list
            in the order the slides came in rather than sorted.

        Example:
            Three slides, two of them from the same lecture, keyed by the path
            of the transcript each one was cut from:

            [lecture5@1882, lecture6@25, lecture5@164]
            -> {
                ".../mediaspace/0_072xwsyi_..._fr.srt": [lecture5@1882, lecture5@164],
                ".../mediaspace/0_c6uyziep_..._fr.srt": [lecture6@25],
            }
        """

        grouped: dict[str, list[BaseResource]] = {}

        for resource in resources:
            if resource.srt_path not in grouped:
                grouped[resource.srt_path] = []
            grouped[resource.srt_path].append(resource)

        return grouped

    def is_slide(self, resource: BaseResource) -> bool:
        """True when a resource is a slide we should append a transcript to."""

        if self.type_subtypes is not None and (resource.type, resource.subtype) not in self.type_subtypes:
            return False

        if resource.mime_type != mt.MARKDOWN:
            return False

        if not resource.is_video or not resource.srt_path:
            return False

        # A slide is named after the second it starts at, so anything else is
        # Markdown that reached here by another route
        return Path(resource.path).stem.isdigit()

    def transform(self, resources: Sequence[BaseResource]) -> list[BaseResource]:
        """Append the spoken words of its interval to every slide resource."""

        slides = []
        transformed_resources: list[BaseResource] = []

        # Split the input in two: slides we have a transcript for, and
        # everything else, which passes through untouched
        for resource in resources:
            if self.is_slide(resource):
                slides.append(resource)
            else:
                transformed_resources.append(resource)

        # One transcript per video, so it is parsed once for all of its slides
        for srt_path, video_slides in self.group_by_video(slides).items():
            try:
                cues = parse_srt(srt_path)
            except OSError as error:
                # Without the transcript there is nothing to append, so the
                # slides keep the text generated by the vision model
                logger.warning(f"Could not read {srt_path}: {error}. Leaving its slides unchanged.")
                transformed_resources.extend(video_slides)
                continue

            # Chronological order is what lets each slide be bounded by the next
            ordered = sorted(video_slides, key=slide_start_seconds)

            for position, resource in enumerate(ordered):
                # A slide runs from its own start to the start of the next one
                # The last slide has no successor, so it runs to the end of the
                # recording, which text_between reads as an open interval
                start = slide_start_seconds(resource)
                if position + 1 < len(ordered):
                    end = slide_start_seconds(ordered[position + 1])
                else:
                    end = None

                # Everything said while this slide was on screen
                spoken = text_between(cues, start, end)

                if not spoken:
                    # A silent stretch, so the slide is left as it is rather
                    # than gaining an empty heading
                    logger.debug(f"Nothing spoken over {resource.title}")
                    transformed_resources.append(resource)
                    continue

                # The path still points at the Markdown ImageToMarkdown wrote,
                # so the transcript is appended to that same file
                md_path = Path(resource.path)
                slide_markdown = md_path.read_text(encoding="utf-8").rstrip()

                # The Markdown is rewritten in place, so a second run over an
                # already-merged file must not append the transcript twice
                starts_quoted = slide_markdown.startswith(TRANSCRIPT_PREFIX)
                contains_quote = f"\n{TRANSCRIPT_PREFIX}" in slide_markdown

                if not starts_quoted and not contains_quote:
                    md_path.write_text(
                        f"{slide_markdown}\n\n{TRANSCRIPT_PREFIX}{spoken}\n",
                        encoding="utf-8",
                    )

                # The subtitles are now part of the chunk, and the file they
                # came from is never copied into the output, so keeping a path
                # to it would only leave a reference that resolves nowhere
                transformed_resources.append(resource.copy_with(srt_path=None))

        return transformed_resources
